Data set idea: weight loss

Variables:
- day - time series
- weight - float
- calories - float
    - split by carbs/protein/fat? put into separate variables by percent?
- target calorie amount - same number throughout
- over/under calorie target
- exercise 
    - boolean?  True/False whether I exercised or not
    - categorical? Listing different exercises (walk, run, yoga class, weight training)
    - estimated calories burned?
    
Run weekly - 52 weeks per year over 2 years = 104 rows
or 
Daily - January-April 2019 inclusive = 119 rows
Can't figure out which would be better

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [15]:
import numpy as np
import scipy.stats as stats

## Weight Loss

Could I do some kind of probability distribution that makes total weight go up/down?

Or have one column with weight lost daily/weekly and then add/subtrct that to total weight in another column?

Weight lost every week: Say I lose an average of 0.5kg per week with a standard deviation of 0.25 and over a normal distribution.

Or with daily say it's 0.1kg per day average with a sd of 0.05g

In [5]:
# Weight lost weekly. 104 rows 

np.random.normal(0.5, 0.25, 104)

array([0.53035613, 0.88478046, 0.55964979, 0.56001733, 0.59667093,
       0.31311551, 0.71914459, 0.67809413, 0.30496321, 0.52273202,
       0.65828197, 0.5751795 , 0.54437432, 0.64022229, 0.49510031,
       0.30394233, 1.00859013, 0.41843989, 0.76184368, 0.76156894,
       0.40020184, 0.83606138, 0.34500748, 0.65119132, 0.0249803 ,
       0.21356769, 0.38433469, 0.74621044, 0.17837976, 0.59223687,
       0.21175965, 0.46613562, 0.73158095, 0.34143563, 0.55083573,
       0.2266482 , 0.59963481, 0.42507242, 0.46561568, 0.60765209,
       0.4592892 , 0.34732109, 0.47363324, 0.30354446, 0.53904869,
       0.09072466, 0.32202275, 0.50179435, 0.21138344, 0.87666462,
       0.5758646 , 0.07212099, 0.59582876, 0.39890941, 0.70957669,
       0.38937595, 1.10469012, 0.40929055, 0.66297524, 0.16667418,
       0.5965485 , 0.725169  , 0.83149832, 0.51265098, 0.17875255,
       0.64616257, 0.45651052, 0.33519331, 1.01582494, 0.37221676,
       0.57066821, 0.84521821, 0.43125035, 0.69635181, 0.78294

In [8]:
# Weight lost daily. 119 rows
np.random.normal(0.1, 0.05, 119)

array([ 0.04823538,  0.05268504,  0.03818897,  0.10028208,  0.15049938,
        0.06705485,  0.19796406,  0.13823963,  0.13301308,  0.08469324,
        0.09915494,  0.09579421,  0.01505269,  0.08865881,  0.02157471,
        0.11173647,  0.10385302,  0.04290503,  0.14916911,  0.03375477,
        0.08418452,  0.11190689,  0.0815706 ,  0.11259532,  0.0479105 ,
        0.22872469,  0.10996354,  0.13157283,  0.03677594,  0.16255123,
       -0.01447738,  0.00881524,  0.10208239,  0.09581126,  0.10159401,
        0.15591235,  0.06051693, -0.01117296,  0.12933462,  0.1059988 ,
        0.17398955,  0.09050691,  0.11695811,  0.05906398,  0.17039902,
       -0.05065568,  0.09080038,  0.14892256,  0.18943022, -0.027365  ,
        0.09096329, -0.01309662,  0.05394154,  0.0447996 ,  0.13082748,
        0.06846907,  0.02682193,  0.16598939,  0.05903173,  0.11247033,
        0.11283234,  0.08292   ,  0.14330124,  0.06922441,  0.08282333,
        0.15810491,  0.05931984,  0.17152016,  0.03285623,  0.14

## Exercise

This makes a case for doing a daily dataset - can't figure out how to do this weekly

Either use randint or random choice

With randint - assign exercises to different integers

None = 1
Walk = 2
Jog = 3
Yoga = 4

With random choice the options are (None, Walk, Jog, Yoga)

Use choice as you can set probability for each option.

Jan-Apr = 119 days = 17 weeks

Say I do some form of exercise about 5 days per week: None = 2 * 17 = 34 days of no exercise = ~28% (make it 29 for 100% probability altogether)

I walk 3 days per week: Walk = 3 * 104 = 51 walks = ~43%

I jog 1 day per week = 17 jogs = ~14%

I have a yoga class about 1 day per week = 17 yoga classes = ~14%


In [9]:
excercises = ["none", "walk", "jog", "yoga"]

np.random.choice(excercises, 119, p=[0.29, 0.43, 0.14, 0.14])

array(['jog', 'walk', 'walk', 'jog', 'walk', 'none', 'yoga', 'walk',
       'none', 'none', 'none', 'walk', 'yoga', 'none', 'jog', 'walk',
       'walk', 'walk', 'jog', 'walk', 'yoga', 'walk', 'walk', 'none',
       'jog', 'walk', 'walk', 'yoga', 'none', 'jog', 'none', 'walk',
       'yoga', 'walk', 'yoga', 'jog', 'walk', 'none', 'none', 'walk',
       'walk', 'yoga', 'walk', 'none', 'walk', 'none', 'jog', 'none',
       'none', 'none', 'jog', 'walk', 'none', 'walk', 'walk', 'yoga',
       'walk', 'none', 'walk', 'walk', 'yoga', 'walk', 'walk', 'none',
       'jog', 'jog', 'walk', 'walk', 'walk', 'walk', 'none', 'none',
       'walk', 'yoga', 'walk', 'none', 'walk', 'jog', 'yoga', 'none',
       'walk', 'walk', 'yoga', 'none', 'none', 'walk', 'walk', 'jog',
       'none', 'yoga', 'walk', 'jog', 'walk', 'walk', 'none', 'none',
       'jog', 'none', 'walk', 'yoga', 'walk', 'walk', 'walk', 'none',
       'yoga', 'none', 'yoga', 'yoga', 'none', 'yoga', 'yoga', 'none',
       'walk', 'jog',

## Calories

Want to aim for 1500 calories per day 

Normal distribution again?

Below shows normal and randint

Maybe a truncated normal distribution as I should never go below 1200 calories but have some days where I'd eat over 2000

In [13]:
np.random.normal(1500, 250, 119)

array([1624.88254971, 1811.02476626, 1768.04569619, 1311.0357598 ,
       1454.96468981, 1649.34037328, 1410.05998199, 1672.30642564,
       1426.85918865, 1820.95370879, 1366.77531938, 2040.6267263 ,
       1614.76043116, 1314.38700067, 1424.16609353, 1441.35959415,
       1342.7526411 , 1370.23697235, 1525.42608285, 1307.82017528,
       1346.14749253, 1997.85829132, 1694.81822478, 1539.16984536,
       1195.25494901, 1392.54834685, 1637.57112677, 1519.58212555,
       1341.06099607, 1622.59002199, 1807.07423666, 1534.11183755,
       1986.47828531, 1590.51650383, 1407.89523301, 1222.0186084 ,
       1286.59311075, 1112.37908084, 1852.11993601, 1414.38764623,
       2103.92814031, 1595.76208711, 1646.23403212, 1432.58422206,
       1853.21034556, 1615.52624808, 1871.46828641, 1330.59431336,
       1421.45829489, 1754.98282721, 1474.20464436, 1327.8536928 ,
        763.64155357, 1713.47176701, 2356.14926579, 1783.95172583,
       1109.17444653, 1405.08005244, 1919.63578326,  943.46026

In [12]:
# or radint for neater values
np.random.randint(1200, 1800, 119)

array([1668, 1540, 1319, 1246, 1215, 1380, 1359, 1709, 1401, 1266, 1691,
       1454, 1561, 1597, 1205, 1476, 1511, 1535, 1606, 1536, 1376, 1659,
       1461, 1501, 1788, 1482, 1491, 1202, 1312, 1369, 1268, 1416, 1413,
       1583, 1716, 1478, 1467, 1552, 1726, 1581, 1269, 1612, 1431, 1300,
       1567, 1233, 1341, 1633, 1528, 1560, 1674, 1248, 1547, 1230, 1683,
       1694, 1267, 1282, 1368, 1394, 1490, 1515, 1517, 1445, 1725, 1688,
       1602, 1542, 1445, 1224, 1370, 1534, 1490, 1259, 1569, 1296, 1496,
       1597, 1528, 1628, 1393, 1425, 1537, 1353, 1228, 1537, 1615, 1451,
       1265, 1557, 1686, 1209, 1353, 1308, 1222, 1738, 1779, 1636, 1372,
       1471, 1416, 1527, 1456, 1468, 1540, 1222, 1759, 1629, 1664, 1228,
       1215, 1747, 1716, 1536, 1227, 1408, 1425, 1598, 1575])

In [23]:
# https://stackoverflow.com/a/18444710
#low = 1200
#high = 2500
#mu = 1500
#sigma = 250

#x = stats.truncnorm((low - mu)/sigma, (high - mu)/sigma, loc=mu, scale=sigma, size=119)
#x


# https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.truncnorm.html
# Figure it out!
stats.truncnorm.rvs(1200, 2500, size = 119)

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf])